// Seed data used if DB tables are empty on first boot.
// Mirrors frontend/src/data/{articles,events}.ts so the app has something
// to show before a real CMS / RSS source is plugged in.

export const SEED_ARTICLES = [
  {
    id: "a-2026-04-20-halving-rocne",
    title: "Rok po halvingu: co se skutečně stalo a co ne",
    excerpt: "Pohled na síťové metriky, hashrate, poplatky a adopci rok po posledním halvingu.",
    body: "Tento článek je zástupný obsah. Až připojíme reálný zdroj (RSS nebo JSON z jednadvacet.org), tahle data se vymění.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-04-20T09:00:00+02:00",
    categories: ["novinky", "makro"],
  },
  {
    id: "a-2026-04-14-seed-self-custody",
    title: "Self-custody pro začátečníky: seed, passphrase a 3 pravidla navíc",
    excerpt: "Praktický návod krok za krokem, který vás nenechá v rozpacích, až budete stát před hardwarem poprvé.",
    body: "Placeholder.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-04-14T18:30:00+02:00",
    categories: ["edukace", "self-custody"],
  },
  {
    id: "a-2026-04-09-lightning-pro-obchody",
    title: "Jak přijímat Lightning v kamenném obchodě (a nezbláznit se)",
    excerpt: "Srovnání BTCPay, Alby Hub a Blink Point-of-Sale z pohledu malého provozovatele.",
    body: "Placeholder.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-04-09T12:10:00+02:00",
    categories: ["lightning", "edukace"],
  },
  {
    id: "a-2026-04-02-privacy-coinjoin-po-samourai",
    title: "Soukromí po Samourai: kam se přesunul CoinJoin v Evropě",
    excerpt: "Přehled dostupných nástrojů a právní situace — co jde legálně a co se v EU zkouší omezit.",
    body: "Placeholder.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-04-02T08:00:00+02:00",
    categories: ["privacy"],
  },
  {
    id: "a-2026-03-25-node-raspi5",
    title: "Vlastní nod na Raspberry Pi 5: kompletní checklist 2026",
    excerpt: "Hardware, SSD, Tor, Umbrel vs. Start9, zálohování kanálů. Co se změnilo od roku 2024.",
    body: "Placeholder.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-03-25T17:45:00+02:00",
    categories: ["technika", "self-custody"],
  },
  {
    id: "a-2026-03-19-bitcoin-prague",
    title: "Bitcoin Prague: předběžný program a praktické tipy",
    excerpt: "Sály, workshopy, doprovodné akce a tipy, kam zajít mimo hlavní program.",
    body: "Placeholder.",
    url: "https://jednadvacet.org/",
    author: "Redakce",
    publishedAt: "2026-03-19T11:00:00+02:00",
    categories: ["konference", "novinky"],
  },
];

export const SEED_EVENTS = [
  {
    id: "e-praha-meetup-kveten",
    title: "Pražský Bitcoin meetup — květen",
    description: "Pravidelné setkání komunity. Neformální, bez přednášek. Přijďte si popovídat.",
    location: "Paralelní Polis, Dělnická 43, Praha 7",
    startsAt: "2026-05-06T19:00:00+02:00",
    endsAt: "2026-05-06T22:00:00+02:00",
    cities: ["praha"],
    categories: ["meetup"],
    organizer: "Jednadvacet Praha",
  },
  {
    id: "e-brno-workshop-lightning",
    title: "Brno workshop: Postav si vlastní Lightning node",
    description: "Praktický workshop. Vezměte si notebook. Vhodné i pro úplné začátečníky.",
    location: "Coworking Brno — místo upřesníme",
    startsAt: "2026-05-15T17:30:00+02:00",
    endsAt: "2026-05-15T21:00:00+02:00",
    cities: ["brno"],
    categories: ["technika", "lightning", "edukace"],
    organizer: "Jednadvacet Brno",
  },
  {
    id: "e-bitcoin-prague-2026",
    title: "Bitcoin Prague 2026",
    description: "Největší evropská bitcoinová konference. Více dní programu, workshopy, meetupy.",
    location: "O2 Universum, Praha 9",
    url: "https://www.btcprague.com/",
    startsAt: "2026-06-18T09:00:00+02:00",
    endsAt: "2026-06-20T18:00:00+02:00",
    cities: ["praha"],
    categories: ["konference"],
    organizer: "Bitcoin Prague",
  },
  {
    id: "e-ostrava-self-custody",
    title: "Ostrava: Self-custody prakticky",
    description: "Hardwarové peněženky, seed backup, passphrase. Přineste si svůj device.",
    location: "Ostrava — místo upřesníme",
    startsAt: "2026-05-22T18:00:00+02:00",
    endsAt: "2026-05-22T20:30:00+02:00",
    cities: ["ostrava"],
    categories: ["self-custody", "edukace"],
    organizer: "Jednadvacet Ostrava",
  },
  {
    id: "e-online-aktualni-makro",
    title: "Online: Makro update (Q2 2026)",
    description: "Stream + diskuse. Sazby, ETF flows, těžaři, regulace. Dotazy přes chat.",
    location: "Online (odkaz přijde registrovaným)",
    startsAt: "2026-05-12T20:00:00+02:00",
    endsAt: "2026-05-12T21:30:00+02:00",
    cities: ["online"],
    categories: ["makro", "edukace"],
    organizer: "Jednadvacet",
  },
  {
    id: "e-bratislava-meetup",
    title: "Bratislava Bitcoin meetup",
    description: "Pravidelný meetup pre slovenskú komunitu. Prídi, dáme pivo a kecáme.",
    location: "Bratislava — miesto spresníme",
    startsAt: "2026-05-28T18:30:00+02:00",
    endsAt: "2026-05-28T22:00:00+02:00",
    cities: ["bratislava"],
    categories: ["meetup"],
    organizer: "Jednadvacet Bratislava",
  },
];
